### ISSUE TITLE
My Health Conditions, strange jump to bottom of page

### ISSUE THREAD

**Issue by remomueller** [myapnea/www.myapnea.org#350]
It's hard to fill out this page without the progress jumping all the way to the bottom when selecting answers to Allergies, Asthma, etc.

https://sleepepi.partners.org/edge/www.myapnea.org/surveys/my-health-conditions

**Comment by mrueschman** [comment]
Happens on "My Sleep Patterns" as well. It seems like the first time through the multi-part question works fine, but then if I try to re-visit the area later on it wants to jump directly to the next question / bottom of the page instead of progressing from question to question within the multi-part area.
