### ISSUE TITLE
Surveys getting loaded multiple times rather than overwritten

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#364]
Example: 
![screen shot 2015-02-25 at 11 51 05 am](https://cloud.githubusercontent.com/assets/4857622/6394466/b53c0fa2-bd9f-11e4-9a9b-6d34f30564d2.png)

**Comment by remomueller** [comment]
Might be related to changing roles, or doing `Survey.load_from_file(...)`

**Comment by pmanko** [comment]
`Survey.load_from_file` updates surveys and does not overwrite them, which is tested for in the related test. @krand7 do you have any more details on when this problem popped up?

**Comment by pmanko** [comment]
I was able to reproduce this problem.

When surveys are launched with different encounters, two answer sessions are made. @krand7 and @remomueller, how should we deal with displaying surveys from different encounters?

I would propose to, for now, just display the most recently created answer session. In the future, we should probably group all answer sessions from a single survey so that users can view their answers across encounters.
