### ISSUE TITLE
If I have not Reviewed Consent or Accepted Privacy Policy I cannot load "Research Surveys"

### ISSUE THREAD

**Issue by mrueschman** [myapnea/www.myapnea.org#382]
1. Sign-up
2. Choose you are diagnosed patient
3. Decline privacy policy
4. Click "Research Surveys" -- the page will never load

Expected behavior would be to send me back to the Privacy Policy to review again (and hopefully accept, etc.)

**Comment by remomueller** [comment]
Might be related and similar to this bug: https://github.com/myapnea/www.myapnea.org/issues/331

**Comment by remomueller** [comment]
Looks like this issue is isolated to our staging server, as we can recreate the same issue on the NSRR staging server URL, and not on the NSRR production server. The main difference is we have an apache front-end on staging, while we have nginx doing the proxy pass on the production server (for both MyApnea.Org and NSRR).

Most likely this will not be an issue in production, but if it is, we can set `data: { no_turbolink: true }` on a few key `link_to` URLs.

**Comment by remomueller** [comment]
The following lines would need the no_turbolink flag.

https://github.com/myapnea/www.myapnea.org/blob/5-0-stable/app/views/layouts/navigation/_right_nav_main.html.haml#L7

https://github.com/myapnea/www.myapnea.org/blob/5-0-stable/app/views/surveys/partials/_survey_progress.html.haml#L26

https://github.com/myapnea/www.myapnea.org/blob/5-0-stable/app/views/surveys/partials/_survey_progress.html.haml#L28
