### ISSUE TITLE
DOB will save and change state even if incorrect format/age

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#453]
From user:

>This may be random incident, but I tried to complete surveys and, as one example I was missing one complete answer for About Me b/c my DOB was incorrect.  It has only two numbers for year.  I could not change it so had to put prefer not to answer to complete the survey.

**Comment by krand7** [comment]
@pmanko All set on the front-end. If the locked DOB question for that user is not just a spot issue, will we need to run another data migration just for that question?

**Comment by pmanko** [comment]
@krand7 The fixes seem to work. When I looked into this problem, the DOB question was not the one missing in that survey. The question shows up locked as it should (since it has been previously answered). However, there were two things that stood out that you might want to take a look at:

- [ ] The styling for `prefer not to answer` on locked does not indicate that the box is locked
- [ ] Client-side validation of the DOB field still occurs even though the text box is locked. We should not have client-side validation of locked answers.
