### ISSUE TITLE
Allow forum posts to be visible pre-moderation

### ISSUE THREAD

**Issue by krand7** [myapnea/www.myapnea.org#520]
Forum posts will be visible with a disclaimer somewhere along the lines of
*"This post has not been reviewed by MyApnea.Org moderators. Please be wary of potential medical advice, etc."*

**Comment by krand7** [comment]
Added internal display changes with 0a66724e4d6824f12c804f65d1d88fee1383935f

**Comment by krand7** [comment]
Instead of 'Not moderated' we could say 'Under review'

**Comment by ekontos** [comment]
I like under review much better.

On May 4, 2015, at 4:59 PM, "Kyle Rand" <notifications@github.com<mailto:notifications@github.com>> wrote:


Instead of 'Not moderated' we could say 'Under review'

—
Reply to this email directly or view it on GitHub<https://github.com/myapnea/www.myapnea.org/issues/520#issuecomment-98848051>.


The information in this e-mail is intended only for the person to whom it is
addressed. If you believe this e-mail was sent to you in error and the e-mail
contains patient information, please contact the Partners Compliance HelpLine at
http://www.partners.org/complianceline . If the e-mail was sent to you in error
but does not contain patient information, please contact the sender and properly
dispose of the e-mail.

**Comment by mrueschman** [comment]
Agreed on "Under review" for the wording.

**Comment by krand7** [comment]
**Next step is to get approval for the disclaimer at the bottom of the thread:**

This topic includes at least one post that has not been approved by a moderator. Please be advised that these posts may contain sensitive material or unsolicitied medical advice. MyApnea does not endorse the content of these posts, and strongly urges you to ignore any direct medical advice received anywhere on the internet.

**Comment by mrueschman** [comment]
I like the disclaimer. If we are compelled to mention medical advice, we could do something similar to CPAPTalk.com's warning:

> The information provided on this site is not intended nor recommended as a substitute for professional medical advice.

**Comment by remomueller** [comment]
I also want to mention that we should change when emails are generated as well, going forward, this should be on post creation, instead of post approval. Also, a user clicking the link would not see the post until logged in, which could also be awkward. Can we change the public view to actually show non-approved posts in some form, with the message, login to see pending posts?

**Comment by mrueschman** [comment]
Latest draft of a bottom-of-forum-topic-disclaimer? @ekontos @krand7 

> This topic includes at least one post that has not been approved by a moderator. Please be advised that these posts may contain sensitive material or unsolicited medical advice. MyApnea does not endorse the content of these posts. The information provided on this site is not intended nor recommended as a substitute for advice from a health care professional who has evaluated you. 

I also discussed with Kyle adding the last sentence as a bullet on the Forum Terms and Conditions.

**Comment by ekontos** [comment]
Looks good.

**Comment by remomueller** [comment]
Hi @mrueschman, I've updated the topic disclaimer to match your post. Is there anything else we need for this issue, or can we close this? (Forum Terms and Conditions could be made into a separate issue if needed).

**Comment by mrueschman** [comment]
Can close, I think.

**Comment by remomueller** [comment]
Thanks, closing issue.
